### ISSUE TITLE
Issue with the "view on explorer" link on NFT tokens

### ISSUE THREAD

**Issue by VDAODAO** [alephium/extension-wallet#118]
<img width="375" alt="Capture d’écran 2023-08-04 à 10 26 39" src="https://github.com/alephium/alephium-nft/assets/42373571/95eb91e2-5fc6-46c7-84ce-273e436a76ab">

When clicking on this button, I expect to be redirected to the NFT page on the explorer, but am instead sent to the homepage of the explorer.

**Comment by h0ngcha0** [comment]
I verified this for testnet and it gets redirected to the NFT contract address page on Explorer. Do you get redirected to https://testnet.alephium.org/?
