### ISSUE TITLE
Clicking on pin notification doesn't do anything

### ISSUE THREAD

**Issue by nop33** [alephium/extension-wallet#65]
After restoring a wallet I got this message on the top right of my screen. Clicking on it, however, didn't pin it on my browser (Brave Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (arm64))

<img width="338" alt="image" src="https://user-images.githubusercontent.com/1579899/224703648-588b4f3a-0d8e-4a80-8f5b-a56c4c131e11.png">

**Comment by polarker** [comment]
I think this is just a reminder so that users would like to pin the extension. Not sure it's able to pin from the web tab.

**Comment by nop33** [comment]
Ah, ok! I expected that clicking on the pin would pin it, thanks for the clarification
