### ISSUE TITLE
Notification click directs to the explorer

### ISSUE THREAD

**Issue by polarker** [alephium/extension-wallet#90]

**Comment by h0ngcha0** [comment]
Some investigations:
1. Callbacks registered using `browser.notifications.onClicked.addListener` are not fired for some reason. 
2. Callbacks registered using `browser.notifications.onClosed.addListener` works.

One suspicion is that the default listener for `browser.notifications.onClicked` triggers the close event, which closes the notification before the newly registered callback receives the click event.

**Comment by polarker** [comment]
@h0ngcha0 I tried Argent-X and clicking on notification windows would go to the explorer. Not sure if we changed anything.

**Comment by h0ngcha0** [comment]
Turns out that `browser.notifications` leverages the desktop notifications which has its own configuration around what happens to a click. For me I use [dunst](https://wiki.archlinux.org/title/Dunst) which by default interprets the left mouse click as closing the notification window
